from pydantic import BaseModel, Field

# Enter /register
class RegisterReq(BaseModel):
    """
        Request model for the /register endpoint.

        Attributes:
            csr_pem_b64 (str): The Base64-encoded PEM string of the Certificate Signing Request (CSR)
                               generated by the client.
    """

    csr_pem_b64: str = Field(..., description="Base64-encoded PEM CSR")


# Leave /register
class RegisterResp(BaseModel):
    """
        Response model for the /register endpoint.

        Attributes:
            uid (str): The newly assigned Unique Identifier for the user.
            cert_pem_b64 (str): The signed X.509 Certificate (Base64 PEM) issued by the CA.
            ca_pub_pem_b64 (str): The CA's Public Key (Base64 PEM) for future verification.
            encrypted_secrets_b64 (str): A blob containing sensitive data (like the Group Key),
                                         encrypted with the user's public key (Hybrid Encryption).
            token_quota (int): The initial number of tokens allocated to the user.
    """

    uid: str
    cert_pem_b64: str
    ca_pub_pem_b64: str
    encrypted_secrets_b64: str
    token_quota: int
