from pydantic import BaseModel, Field
from typing import List

# Enter /tokens
class TokensReq(BaseModel):
    """
        Request model for the /tokens endpoint.

        Attributes:
            uid (str): The Unique Identifier of the user requesting tokens.
            count (int): The number of tokens requested (must be between 1 and 100).
    """

    uid: str
    count: int = Field(ge=1, le=100)

# Leave /tokens
class TokensResp(BaseModel):
    """
        Response model for the /tokens endpoint.

        Attributes:
            uid (str): The user ID associated with the issuance.
            issued (List[str]): A list of unique Token IDs generated by the CA.
    """

    uid: str
    issued: List[str]